-- MySQL Script generated by MySQL Workbench
-- Thu Sep 22 06:24:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Veículo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Veículo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Veículo` (
  `idVeículo` INT NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  `Montadora` VARCHAR(45) NULL,
  `Kilometragem` VARCHAR(45) NULL,
  PRIMARY KEY (`idVeículo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Veículo_idVeículo` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `Veículo_idVeículo`),
  INDEX `fk_Cliente_Veículo_idx` (`Veículo_idVeículo` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Veículo`
    FOREIGN KEY (`Veículo_idVeículo`)
    REFERENCES `mydb`.`Veículo` (`idVeículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe de Mecânicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe de Mecânicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe de Mecânicos` (
  `idEquipe de Mecânicos` INT NOT NULL,
  `Avaliação` VARCHAR(45) NULL,
  `Execução` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe de Mecânicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ordem de Serviço` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Número` VARCHAR(45) NULL,
  `Data de Emissão` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `Valor Total` VARCHAR(45) NULL,
  `Autorização do Cliente` VARCHAR(45) NULL,
  `Data de Entrega` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Cliente_Veículo_idVeículo` INT NOT NULL,
  `Equipe de Mecânicos_idEquipe de Mecânicos` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Cliente_idCliente`, `Cliente_Veículo_idVeículo`, `Equipe de Mecânicos_idEquipe de Mecânicos`),
  INDEX `fk_Ordem de Serviço_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_Veículo_idVeículo` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Equipe de Mecânicos1_idx` (`Equipe de Mecânicos_idEquipe de Mecânicos` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_Veículo_idVeículo`)
    REFERENCES `mydb`.`Cliente` (`idCliente` , `Veículo_idVeículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Equipe de Mecânicos1`
    FOREIGN KEY (`Equipe de Mecânicos_idEquipe de Mecânicos`)
    REFERENCES `mydb`.`Equipe de Mecânicos` (`idEquipe de Mecânicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecânico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mecânico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mecânico` (
  `idMecânico` INT NOT NULL,
  `Código` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMecânico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Valor da Mão de Obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Valor da Mão de Obra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Valor da Mão de Obra` (
  `idValor da Mão de Obra` INT NOT NULL,
  `Descrição do Serviço` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idValor da Mão de Obra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Valor das Peças`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Valor das Peças` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Valor das Peças` (
  `idPeças` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeças`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peças Utilizadas no Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Peças Utilizadas no Serviço` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Peças Utilizadas no Serviço` (
  `Peças_idValor das Peças` INT NOT NULL,
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`Peças_idValor das Peças`, `Ordem de Serviço_idOrdem de Serviço`),
  INDEX `fk_Peças_has_Ordem de Serviço_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC) VISIBLE,
  INDEX `fk_Peças_has_Ordem de Serviço_Peças1_idx` (`Peças_idValor das Peças` ASC) VISIBLE,
  CONSTRAINT `fk_Peças_has_Ordem de Serviço_Peças1`
    FOREIGN KEY (`Peças_idValor das Peças`)
    REFERENCES `mydb`.`Valor das Peças` (`idPeças`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Peças_has_Ordem de Serviço_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mão de Obra do Serviço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mão de Obra do Serviço` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mão de Obra do Serviço` (
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  `Mão de Obra_idMão de Obra` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`Ordem de Serviço_idOrdem de Serviço`, `Mão de Obra_idMão de Obra`),
  INDEX `fk_Ordem de Serviço_has_Mão de Obra_Mão de Obra1_idx` (`Mão de Obra_idMão de Obra` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_has_Mão de Obra_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_has_Mão de Obra_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_has_Mão de Obra_Mão de Obra1`
    FOREIGN KEY (`Mão de Obra_idMão de Obra`)
    REFERENCES `mydb`.`Valor da Mão de Obra` (`idValor da Mão de Obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Composição da Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Composição da Equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Composição da Equipe` (
  `Equipe de Mecânicos_idEquipe de Mecânicos` INT NOT NULL,
  `Mecânico_idMecânico` INT NOT NULL,
  PRIMARY KEY (`Equipe de Mecânicos_idEquipe de Mecânicos`, `Mecânico_idMecânico`),
  INDEX `fk_Equipe de Mecânicos_has_Mecânico_Mecânico1_idx` (`Mecânico_idMecânico` ASC) VISIBLE,
  INDEX `fk_Equipe de Mecânicos_has_Mecânico_Equipe de Mecânicos1_idx` (`Equipe de Mecânicos_idEquipe de Mecânicos` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe de Mecânicos_has_Mecânico_Equipe de Mecânicos1`
    FOREIGN KEY (`Equipe de Mecânicos_idEquipe de Mecânicos`)
    REFERENCES `mydb`.`Equipe de Mecânicos` (`idEquipe de Mecânicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe de Mecânicos_has_Mecânico_Mecânico1`
    FOREIGN KEY (`Mecânico_idMecânico`)
    REFERENCES `mydb`.`Mecânico` (`idMecânico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;